/* SPDX-License-Identifier: BSD-2-Clause
 *
 * Thunderscope library
 *
 * Copyright (C) 2024 / Nate Meyer  / nate.devel@gmail.com
 *
 */
#ifndef _PLATFORM_H_
#define _PLATFORM_H_

#include "ts_common.h"
#include "csr.h"


#define TS_SPI_BUS_BASE_ADDR    CSR_MAIN_SPI_BASE    
#define TS_SPI_BUS_CS_NUM       (CSR_MAIN_SPI_CS_SEL_SIZE)
#define TS_ADC_CS               (0)
#define TS_AFE_0_AMP_CS         (1)
#define TS_AFE_1_AMP_CS         (2)
#define TS_AFE_2_AMP_CS         (3)
#define TS_AFE_3_AMP_CS         (4)

#define TS_I2C_BASE_ADDR        CSR_I2C_BASE

#define TS_TRIM_DAC_I2C_ADDR    (0x60)
#define TS_TRIM_DPOT_I2C_ADDR   (0x2C)

#define TS_PLL_I2C_ADDR         (0x74)

#define TS_AFE_0_TERM_REG       CSR_FRONTEND_CONTROL_ADDR
#define TS_AFE_0_TERM_MASK      (1 << 20)

#define TS_AFE_1_TERM_REG       CSR_FRONTEND_CONTROL_ADDR
#define TS_AFE_1_TERM_MASK      (1 << 21)

#define TS_AFE_2_TERM_REG       CSR_FRONTEND_CONTROL_ADDR
#define TS_AFE_2_TERM_MASK      (1 << 22)

#define TS_AFE_3_TERM_REG       CSR_FRONTEND_CONTROL_ADDR
#define TS_AFE_3_TERM_MASK      (1 << 23)

#define TS_AFE_0_ATTEN_REG      CSR_FRONTEND_CONTROL_ADDR
#define TS_AFE_0_ATTEN_MASK     (1 << (CSR_FRONTEND_CONTROL_ATTENUATION_OFFSET))

#define TS_AFE_1_ATTEN_REG      CSR_FRONTEND_CONTROL_ADDR
#define TS_AFE_1_ATTEN_MASK     (1 << (CSR_FRONTEND_CONTROL_ATTENUATION_OFFSET + 1))

#define TS_AFE_2_ATTEN_REG      CSR_FRONTEND_CONTROL_ADDR
#define TS_AFE_2_ATTEN_MASK     (1 << (CSR_FRONTEND_CONTROL_ATTENUATION_OFFSET + 2))

#define TS_AFE_3_ATTEN_REG      CSR_FRONTEND_CONTROL_ADDR
#define TS_AFE_3_ATTEN_MASK     (1 << (CSR_FRONTEND_CONTROL_ATTENUATION_OFFSET + 3))

#define TS_AFE_0_COUPLING_REG   CSR_FRONTEND_CONTROL_ADDR
#define TS_AFE_0_COUPLING_MASK  (1 << (CSR_FRONTEND_CONTROL_COUPLING_OFFSET))

#define TS_AFE_1_COUPLING_REG   CSR_FRONTEND_CONTROL_ADDR
#define TS_AFE_1_COUPLING_MASK  (1 << (CSR_FRONTEND_CONTROL_COUPLING_OFFSET + 1))

#define TS_AFE_2_COUPLING_REG   CSR_FRONTEND_CONTROL_ADDR
#define TS_AFE_2_COUPLING_MASK  (1 << (CSR_FRONTEND_CONTROL_COUPLING_OFFSET + 2))

#define TS_AFE_3_COUPLING_REG   CSR_FRONTEND_CONTROL_ADDR
#define TS_AFE_3_COUPLING_MASK  (1 << (CSR_FRONTEND_CONTROL_COUPLING_OFFSET + 3))



#endif