//--------------------------------------------------------------------------------
// Auto-generated by LiteX (a1ea5a2f6) on 2025-08-29 22:49:50
//--------------------------------------------------------------------------------
#ifndef __GENERATED_SOC_H
#define __GENERATED_SOC_H
#define CONFIG_PLATFORM_NAME "thunderscope"
#define CONFIG_CLOCK_FREQUENCY 150000000
#define CONFIG_CPU_TYPE_NONE
#define CONFIG_CPU_VARIANT_STANDARD
#define CONFIG_CPU_FAMILY
#define CONFIG_CPU_NAME
#define CONFIG_CPU_HUMAN_NAME "Unknown"
#define CONFIG_IDENTIFIER "LitePCIe SoC on ThunderScope DEV (0.2.0-next-66d756e-20250829-dirty) 2025-08-29 22:49:49"
#define DMA_CHANNELS 1
#define DMA_ADDR_WIDTH 64
#define PCIE_DMA0_READER_INTERRUPT 0
#define PCIE_DMA0_WRITER_INTERRUPT 1
#define SPIFLASH_PHY_FREQUENCY 37500000
#define SPIFLASH_MODULE_NAME "mx25u6435e"
#define SPIFLASH_MODULE_TOTAL_SIZE 8388608
#define SPIFLASH_MODULE_PAGE_SIZE 256
#define SPIFLASH_MODULE_QUAD_CAPABLE
#define CONFIG_CSR_DATA_WIDTH 32
#define CONFIG_CSR_ALIGNMENT 32
#define CONFIG_BUS_STANDARD "wishbone"
#define CONFIG_BUS_DATA_WIDTH 32
#define CONFIG_BUS_ADDRESS_WIDTH 32
#define CONFIG_BUS_BURSTING 0

#endif
