//--------------------------------------------------------------------------------
// Auto-generated by LiteX (f63d4a833) on 2024-12-26 19:07:59
//--------------------------------------------------------------------------------
#ifndef __GENERATED_SOC_H
#define __GENERATED_SOC_H
#define CONFIG_PLATFORM_NAME "thunderscope"
#define CONFIG_CLOCK_FREQUENCY 150000000
#define CONFIG_CPU_TYPE_NONE
#define CONFIG_CPU_VARIANT_STANDARD
#define CONFIG_CPU_FAMILY
#define CONFIG_CPU_NAME
#define CONFIG_CPU_HUMAN_NAME "Unknown"
#define CONFIG_IDENTIFIER "LitePCIe SoC on ThunderScope A200T (dca96645) 2024-12-26 19:07:58"
#define DMA_CHANNELS 1
#define DMA_ADDR_WIDTH 64
#define PCIE_DMA0_READER_INTERRUPT 0
#define PCIE_DMA0_WRITER_INTERRUPT 1
#define SPIFLASH_PHY_FREQUENCY 37500000
#define SPIFLASH_MODULE_NAME "s25fl256s"
#define SPIFLASH_MODULE_TOTAL_SIZE 33554432
#define SPIFLASH_MODULE_PAGE_SIZE 256
#define CONFIG_CSR_DATA_WIDTH 32
#define CONFIG_CSR_ALIGNMENT 32
#define CONFIG_BUS_STANDARD "wishbone"
#define CONFIG_BUS_DATA_WIDTH 32
#define CONFIG_BUS_ADDRESS_WIDTH 32
#define CONFIG_BUS_BURSTING 0

#endif
